feat: add transfer page
Greenstand/treetracker-web-map-core-demo pull request #31
Opened 2023-08-26 20:46 UTC by dagmawig

fixes #24

2023-08-26 20:48 UTC, dagmawig commented
@pierrelstan  please review.

2023-08-29 03:24 UTC, dadiorchen commented
@dagmawig is it easy for you to add screenshot for this?

2023-08-29 16:32 UTC, pierrelstan commented
@dagmawig  please resolve the conflicts

2023-08-31 23:54 UTC, pierrelstan commented on src/screens/TransferScreen.tsx
> +  const ArrowLeft = (props: SvgProps) => (
Add the svgs to the Icons component.

2023-09-01 00:00 UTC, pierrelstan commented on src/screens/TransferScreen.tsx
> +      <View style={style.header}>
Use the header that from the react navigation

2023-09-01 00:04 UTC, pierrelstan commented on src/screens/TransferScreen.tsx
> +        <View>{ArrowDown(null)}</View>
Add the svgs icons as a component.  

for example: 
`<Header />`

2023-09-01 00:07 UTC, pierrelstan commented on src/screens/TransferScreen.tsx
> +          style={{
Reduce the inline css.

2023-09-01 00:14 UTC, pierrelstan requested changes
Replace  the textInputcomponent to  customInput component and customize it (customInput) to make it dynamic.
Do the same for the CustomButton component.

2023-09-02 23:18 UTC, dagmawig commented
> @dagmawig is it easy for you to add screenshot for this?

![image](https://github.com/Greenstand/treetracker-web-map-core-demo/assets/61099792/c8d24c51-3027-47b5-b453-f342b383e89a)

2023-09-03 01:58 UTC, pierrelstan approved these changes

2023-09-03 01:58 UTC, merged

2023-09-03 02:05 UTC, pierrelstan commented
great Work @dagmawig